### ISSUE TITLE
Can't use TAB.

### ISSUE THREAD

**Issue by CrystalBlaade** [otavioschwanck/doom_emacs_dotfiles#2]
Hello! I've been using this config for a while and it was perfect. But after fresh re-installation i can't use TAB to insert "spaces" or use autocomplete.
Im using Emacs 27.2 with Solus Linux 4.3.

**Comment by the-moriarty** [comment]
> Hello! I've been using this config for a while and it was perfect. But after fresh re-installation i can't use TAB to insert "spaces" or use autocomplete. Im using Emacs 27.2 with Solus Linux 4.3.

Hi @CrystalBlaade , the reason of that is because tab is mapped only for snippets.  See the autocomplete and snippets session on the Handbook or the gif in readme.

The reason i did that is to autocomplete and snippets dont get in way of each other (its so annoying when happens).

To go forward and backward on autocomplete list, press C-n and C-p, to select, ENTER.  To expand snippet, is tab.

To see all snippets press M-x yas-describe-tables

But anyways, i did a fix to when dont have snippets to expand, it insert normal tabs.

https://github.com/otavioschwanck/doom-emacs-on-rails/commit/71db7b66db16f7e74c7cd469a678db6617446d19

About the tabs, some alternatives that i use:

Select with V and press = to indent to tab
SPC - indent whole file
SPC = run rubocop on file
>> and << in normal mode or > and < on visual mode change indentation of the line.

If your issue is solved, please close the issue, thanks!

**Comment by otavioschwanck** [comment]
> Hello! I've been using this config for a while and it was perfect. But after fresh re-installation i can't use TAB to insert "spaces" or use autocomplete. Im using Emacs 27.2 with Solus Linux 4.3.

Hi @CrystalBlaade , the reason of that is because tab is mapped only for snippets.  See the autocomplete and snippets session on the Handbook or the gif in readme.

The reason i did that is to autocomplete and snippets dont get in way of each other (its so annoying when happens).

To go forward and backward on autocomplete list, press C-n and C-p, to select, ENTER.  To expand snippet, is tab.

To see all snippets press `M-x yas-describe-tables`

But anyways, i did a fix to when dont have snippets to expand, it insert normal tabs.

https://github.com/otavioschwanck/doom-emacs-on-rails/commit/71db7b66db16f7e74c7cd469a678db6617446d19

About the tabs, some alternatives that i use:

```
Select with V and press = to indent to tab
SPC - indent whole file
SPC = run rubocop on file
>> and << in normal mode or > and < on visual mode change indentation of the line.
```
![image](https://user-images.githubusercontent.com/9551316/149812552-502fdefb-aa57-4860-8962-5942c0990afb.png)

Gif of how to use autocomplete: https://github.com/otavioschwanck/doom-emacs-on-rails/blob/master/autocomplete.gif

If your issue is solved, please close this issue, thanks!

**Comment by otavioschwanck** [comment]
Good news:  I bring back tab to autocomplete.   Now for snippets, you can use C-o.

![image](https://user-images.githubusercontent.com/9551316/149819760-2d1cc9d0-c134-482f-93bb-aa6729da8721.png)

See the announcements on the project README. <3

**Comment by CrystalBlaade** [comment]
Thank's for your reply!
